### ISSUE TITLE
Default titanium bin not found

### ISSUE THREAD

**Issue by iRonin** [MattTuttle/sublime-ti-build#35]
I get

```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/titanium'
```

while

```
which titanium
/usr/local/bin/titanium
```

Wouldn't it be better to use simple `titanium` [here](https://github.com/MattTuttle/sublime-ti-build/blob/master/Titanium.py#L11) instead of the path?

**Comment by MattTuttle** [comment]
Some platforms don't work properly with just `titanium` so we had to include the full path. You can change the path in your settings file to `/usr/local/bin/titanium` or make a symlink if that is supported on your platform.

**Comment by iRonin** [comment]
Some does not work with `/usr/bin/titanium` either :)
